name: Check
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Node version
        run: node -v
      - name: Yarn version
        run: yarn -v
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test-with-coverage
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./coverage/
      - name: Build
        run: yarn build
