name: Doc Site
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Run Npm Scripts
        run: |
          node -v
          yarn -v
          yarn install
          yarn run build-doc
      - name: Deploy to Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'antd-mobile-${{ github.sha }}.surge.sh'
          project: './dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Create Commit Comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Doc site for this release: https://antd-mobile-${{ github.sha }}.surge.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: mobile.ant.design
